name: interventions
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.13
  - pandas
  - numpy
  - seaborn
  - matplotlib
  - tqdm
  - moreutils
  - datasets
  - scikit-learn
  - coloredlogs
  - shap
  - pip
  - pip:
      - syndisco